// F0 bridge regression tests: H3 (plaintext wipe), H4 (failed state), C4 (ACK suppress).
#include "tgverity/bridge.h"
#include "tgverity/crypto_provider.h"
#include "tgverity/fake_telegram_client.h"
#include "tgverity/relay_packet.h"
#include "tgverity/state_machine.h"

#include <cassert>
#include <iostream>

int main() {
    using namespace tgverity;

    IdentityCryptoProvider crypto;

    // ---- H3: Plaintext wipe on cleanup_done ----
    {
        FakeTelegramClient alice;
        FakeTelegramClient bob;
        alice.setPeerDeliverer([&](const std::string& c, const std::string& s, const std::string& t) {
            bob.receiveFromWire(c, s, t);
        });
        bob.setPeerDeliverer([&](const std::string& c, const std::string& s, const std::string& t) {
            alice.receiveFromWire(c, s, t);
        });
        Bridge aBridge(crypto, alice);
        Bridge bBridge(crypto, bob);

        const auto pid = aBridge.send("chat-h3", "hello-h3");
        const auto* ob = aBridge.outbound(pid);
        assert(ob != nullptr);
        assert(ob->status == MessageStatus::cleanup_done);
        assert(ob->plaintext.empty()); // H3: plaintext wiped on cleanup_done

        const auto* im = bBridge.inbound(pid);
        assert(im != nullptr);
        assert(im->status == MessageStatus::cleanup_done);
        assert(im->plaintext.empty()); // H3: inbound plaintext also wiped
    }

    // ---- H4: Decrypt failure -> failed state ----
    {
        // Create a packet that will fail decryption by corrupting the body.
        // IdentityCryptoProvider just returns plaintext, so we forge a packet
        // where the body is different from what the session expects.
        // Better approach: use a chat that has no session context.
        // The parser will succeed but recordInbound will reject replay.
        // To test H4, we need a scenario where crypto.open() returns nullopt.
        // Since IdentityCryptoProvider always succeeds, we test via a separate
        // crypto that fails: construct a bridge where the provider rejects.

        class FailingCrypto : public CryptoProvider {
        public:
            CryptoSuite suiteId() const override { return CryptoSuite::Identity; }
            Bytes seal(const Bytes& plaintext, const Bytes& aad) const override {
                return plaintext;
            }
            std::optional<Bytes> open(const Bytes& ciphertext, const Bytes& aad) const override {
                return std::nullopt; // always fail
            }
        };

        FailingCrypto failCrypto;
        FakeTelegramClient alice;
        FakeTelegramClient bob;
        alice.setPeerDeliverer([&](const std::string& c, const std::string& s, const std::string& t) {
            bob.receiveFromWire(c, s, t);
        });
        bob.setPeerDeliverer([&](const std::string& c, const std::string& s, const std::string& t) {
            alice.receiveFromWire(c, s, t);
        });
        Bridge aBridgeFail(failCrypto, alice);
        Bridge bBridgeFail(failCrypto, bob);

        const auto pid = aBridgeFail.send("chat-h4", "hello-h4");

        // Bob's bridge receives the packet; decrypt fails -> failed state.
        const auto* im = bBridgeFail.inbound(pid);
        assert(im != nullptr);
        assert(im->status == MessageStatus::failed); // H4: decrypt failure -> failed
    }

    // ---- C4: ACK suppression ----
    {
        FakeTelegramClient alice;
        FakeTelegramClient bob;
        alice.setPeerDeliverer([&](const std::string& c, const std::string& s, const std::string& t) {
            bob.receiveFromWire(c, s, t);
        });
        bob.setPeerDeliverer([&](const std::string& c, const std::string& s, const std::string& t) {
            alice.receiveFromWire(c, s, t);
        });
        Bridge aBridge(crypto, alice);
        Bridge bBridge(crypto, bob);

        const auto pid = aBridge.send("chat-c4", "hello-c4");

        // Alice receives the ACK — C4: suppress hooks must be called.
        // Alice sent MSG; Bob receives, suppresses, decrypts, renders virtual, sends ACK;
        // Alice receives ACK. Check that suppress hooks were called for the ACK's serverId.
        // The ACK serverId is generated by FakeTelegramClient (srv-N).
        // We verify by checking that suppress hooks were called (not empty).
        assert(!alice.suppressedRenderIds().empty());
        assert(!alice.suppressedNotificationIds().empty());
        assert(!alice.suppressedEditIds().empty());
    }

    std::cout << "bridge_f0_tests passed\n";
    return 0;
}